### ISSUE TITLE
Add Code of Conduct below the Registration Button

### ISSUE THREAD

**Issue by gtke** [uniHackio/2015f.hacktbilisi.com#1]
http://static.mlh.io/docs/event-sanctioning-guide.pdf

**Comment by safareli** [comment]
are you sure url is correct?
i think we should use this http://static.mlh.io/docs/mlh-code-of-conduct.pdf

**Comment by safareli** [comment]
this link seems incorect we should use http://static.mlh.io/docs/mlh-code-of-conduct.pdf
and we don't need it to be below registration button and instead have it in registration form like [bathhack](http://bathhack.com/) has.
so I need unapply my commit.
